version: "3"

services:
  book_store:
    ports: 
      - 5000:5000
    volumes: 
      - .:/book_store/server
      - node_modules:/book_store/server/node_modules

  postgres:
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=book_store
    ports: 
      - 5432:5432

volumes:
  node_modules: